# Generated by Django 3.1 on 2022-06-01 09:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('branch_id', models.IntegerField()),
                ('unversal_profile_id', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('service_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilerule.servicegroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilerule.template')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGroupBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilerule.branch')),
                ('service_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilerule.servicegroup')),
            ],
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilerule.template'),
        ),
        migrations.CreateModel(
            name='QueuesProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.IntegerField()),
                ('profile_id', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilerule.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profilerule.template'),
        ),
        migrations.CreateModel(
            name='AllowedProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilerule.branch')),
            ],
        ),
    ]
