# Generated by Django 3.1 on 2022-06-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilerule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedProfiles',
        ),
    ]
