# Generated by Django 3.1 on 2022-06-01 09:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilerule', '0002_delete_allowedprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilerule.branch')),
            ],
        ),
    ]
