# Generated by Django 3.1 on 2022-06-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilerule', '0003_allowedprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroup',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profilerule.template'),
        ),
    ]
