# Generated by Django 4.0.5 on 2022-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilerule', '0004_auto_20220602_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
